stages:
  - build
  - deploy
  
variables:
  TARGET_DIR: /home/portfolio/


build:
  stage: build
  script: 
    - echo "Deploy to staging server"
    - cp -r -rf $CI_PROJECT_DIR/* /home/portfolio/

  only:
    - production

deploy to server:
  stage: deploy
  script:
    - cd /home/portfolio 
    - npm install
    - npm upgrade
    - npm run build
    - echo "finished building frontend"
  only:
    - production 
  when: manual
